# Generated by Django 4.2.5 on 2023-09-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('unique_identity', models.CharField(max_length=200)),
                ('criminal_image', models.FileField(upload_to='')),
                ('crime_type', models.CharField(max_length=200)),
                ('crime_desc', models.TextField()),
            ],
        ),
    ]
